---
name: AGP

on:
  schedule:
    - cron: "0 * * * *" #hourly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push/v1
    token: ${{ secrets.CI_TOKEN }}
---
name: AGP

on:
  schedule:
    - cron: "0 * * * *" # hourly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
